openapi: 3.0.1
info:
  title: Get Geometry Type API
  description: |-
    This API returns the geometry type of a single dataset (Line/Point /Polygon/Multi Geometry).<br><br><hr><br>[<img src="https://about.mappls.com/images/mappls-logo.svg" height="60"/> </p>](https://about.mappls.com/api/)
    
      On a Mission to <b>"Make our world better through maps, location technologies & IoT"</b>, MapmyIndia is continuously enabling real time hyper-local information access through its map & location services. mGIS APIs are a part of mGIS platform and the document describes APIs usage and specifications for their integration into an application. The document covers :
    <ul><li>List of APIs</ul></li> 
    <ul><li>Explanation of resources and query parameters</ul></li>
    <ul><li>Listing of response structure</ul></li>

    ## Important notes
     <ul><li><b>URLs</b>: the urls to use for UAT and Production are:  <ul><li>
     <b>Production</b>:
    <code>https://mgis-api.mappls.com/</code></li><li>
     <b>UAT</b>:<code>https://mgis-preprod.mappls.in/</code><li> To call our API, the
    endpoint requires access-token authorization and the <code>access-token</code> needs to be entered. For example <code>https://mgis.mappls.in/getFeatureCentroid </code> <br> Pass header as <code>Authorization:Bearer access_token</code>   </li> </ul> <li>For any issues or questions please submit it to our support : <a href="mailto:apisupport@mapmyindia.com" target="_blank">API Support</a>.  If you have some non-technical or commercial queries, contact your service account manager</li></ul>
  contact:
    name: MapmyIndia API Support
    url: 'https://www.mapmyindia.com/api/#f_cont'
    email: apisupport@mapmyindia.com
  termsOfService: 'https://www.mapmyindia.com/api/terms-&-conditions'
  version: V1.0.0
tags:
  - name: Get Geometry Type API
    description: Fetches the bounds of feature(s) of the dataset published in the corresponding workspace of the user.
servers:
  - url: 'https://mgis-api.mappls.com/'
    description: Production server for mGIS APIs
  - url: 'https://mgis-preprod.mappls.in/'
    description: UAT server for mGIS APIs testing
paths:
  /getGeometryType:
    get:
      tags:
        - Get Geometry Type API
      summary: Fetches Geometry type of datasetNme
      description: Fetches Geometry type of datasetNme
      operationId: getgeometryID
      parameters:
        - $ref: '#/components/parameters/datasetNmeParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getGeometryType'
        '400':
          description: 'Bad Request, User made an error while creating a valid request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject400'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObjectCommon'
        '404':
          description: No data found in database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObjectCommon'
        '422':
          description: Parameter missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObjectCommon'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject500'
components:
  parameters:
    datasetNmeParam:
      name: datasetNme
      in: query
      description: The dataset name whose feature centroid or geometry is required.
      required: true
      allowEmptyValue: false
      schema:
        type: string
      example: india
    featureIDParam:
      name: featureID
      in: query
      description: The feature id of the dataset of whose centroid is to be fetched.
      required: true
      allowEmptyValue: false
      schema:
        type: number
      example: 1
  schemas:
    getGeometryType:
      title: getGeometryType
      type: object
      properties:
        geometryType:
          type: string
          description: layer's Geometry Type
          example: linestring
    ErrorObjectCommon:
      title: ErrorObject
      type: object
      properties:
        code:
          type: string
          description: Error code.
          example: '422'
        error:
          type: string
          description: Different error messages that might have occured while making a particular request to the server
          example: Bad request. Username not found.
    ErrorObject400:
      title: Geoserver ErrorObject
      type: object
      properties:
        error:
          type: string
          description: Different error messages that might have occured while making a particular request to the server
          example: Invalid Parameter value
        message:
          type: string
          description: Different error messages that might have occured while making a particular request to the server
          example: Layer not found.
        auth:
          type: string
          example: unsuccessful
        code:
          type: number
          description: Error code.
          example: 400
    ErrorObject500:
      title: Internal Server ErrorObject
      type: object
      properties:
        code:
          type: string
          description: Error code.
          example: '500'
        error:
          type: string
          description: Different error messages that might have occured while making a particular request to the server
          example: Something went wrong.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
